ORG 0
	DIP_SW 	EQU 0800H
	LED1 	EQU 2000H
	LED2 	EQU 2800H
	LED3 	EQU 3000H
	LED4 	EQU 3800H
	ROW 	EQU 1000H
	COLUMN 	EQU 1800H
//------------------------------
MAIN:
	MOV TMOD, #00010101B
	CALL CLEARING_LED
	CALL CLEARING_MATRIX						 
	MOV A, #0F7H
	MOV P1, A				 
	JB P1.4, $				  
	CALL SELECT_RULER								 
//------------------------------

CLEARING_LED:
	MOV DPTR, #LED4
	CALL ERASER
	MOV DPTR, #LED3
	CALL ERASER
	MOV DPTR, #LED2
	CALL ERASER
	MOV DPTR, #LED1
	CALL ERASER
	RET
ERASER:
	MOV A, #0FFH
	MOVX @DPTR, A
	RET
;-------------------------------
CLEARING_MATRIX:
	MOV A, #0FFH
	MOV DPTR, #ROW
	MOVX @DPTR, A
	RET
;-------------------------------
SELECT_RULER:
	MOV DPTR, #DIP_SW
	MOVX A, @DPTR
	MOV R5, A
	CJNE A, #1, NEXT
	SJMP CASE_Hz
	NEXT:
	CJNE A, #2, NEXT1
	SJMP CASE_kHz
	NEXT1:
	CJNE A, #4, NEXT2
	SJMP CASE_MHz
	NEXT2: 
	JMP SELECT_RULER
;--------------------------------
CASE_Hz:
	SETB P3.4
	MOV TL0, #0
	MOV TH0, #0
	MOV R7, #200
	SETB TR0
	AGAIN:
	MOV TL1, #LOW(-4989)
	MOV TH1, #HIGH(-4989)
	SETB TR1
	JNB TF1, $
	CLR TR1
	CLR TF1
	DJNZ R7, AGAIN
	MOV R6, #99
	DJNZ R6, $
	CLR TR0
	MOV A, TL0
	MOV R6, TH0
	CALL PROCESSING
	CALL DISPLAY
	MOV DPTR, #TAB_H
	CALL UNIT_FREQUENCY
;--------------------------------
CASE_kHz:
	SETB P3.4
	MOV TL0, #0
	MOV TH0, #0
	MOV TL1, #LOW(-995)
	MOV TH1, #HIGH(-995)
	SETB TR0
	SETB TR1  
	JNB TF1, $
	CLR TR1	 
	CLR TF1	 		 
	CLR TR0
	MOV A, TL0
	MOV R6, TH0
	CALL PROCESSING
	CALL DISPLAY
	MOV DPTR, #TAB_K
	CALL UNIT_FREQUENCY
;---------------------------------
CASE_MHz:
	SETB P3.4
	MOV TL0, #0
	MOV TH0, #0
	SETB TR0
	CLR TR0
	MOV A, TL0
	MOV R6, TH0
	CALL PROCESSING
	CALL DISPLAY
	MOV DPTR, #TAB_M
	CALL UNIT_FREQUENCY
;----------------------------------
ENDING:
	PUSH ACC
	MOV A, #0F7H
	MOV P1, A	
	JNB P1.6, NEXT_STEP
	POP ACC
	RET
	NEXT_STEP:
	JMP MAIN
;----------------------------------
UNIT_FREQUENCY:
	MOV A, #1H
	MOV R0, #0
LOOP:
	PUSH DPH
	PUSH DPL
	MOV DPTR, #COLUMN
	MOVX @DPTR, A
	POP DPL
	POP DPH
	CALL SWEEP_ROW
	RL A
	CALL DELAY
	CALL ENDING
	JMP LOOP

SWEEP_ROW:
	PUSH ACC
	MOV A, R0
	MOVC A, @A+DPTR
	PUSH DPH
	PUSH DPL
	MOV DPTR, #ROW
	MOVX @DPTR, A
	POP DPL
	POP DPH
	INC R0
	MOV A, R0
	CJNE A, #8H, CONTINUE
	MOV R0, #0
	POP ACC
	RET
	CONTINUE:
	POP ACC
	RET

TAB_H: DB 0FFH, 0FFH, 83H, 0EFH, 0EFH, 83H, 0FFH, 0FFH
TAB_K: DB 0FFH, 0FFH, 81H, 0E7H, 0DBH, 0BDH, 0FFH, 0FFH
TAB_M: DB 0FFH, 81H, 0FBH, 0F7H, 0F7H, 0FBH, 081H, 0FFH
;----------------------------------------
DISPLAY:
	MOV DPTR, #TAB_LED
	MOV A, R2
	MOVC A, @A+DPTR
	MOV DPTR, #LED1
	MOVX @DPTR, A

	MOV DPTR, #TAB_LED
	MOV A, R1
	MOVC A, @A+DPTR
	MOV DPTR, #LED2
	MOVX @DPTR, A

	MOV DPTR, #TAB_LED
	MOV A, R0
	MOVC A, @A+DPTR
	MOV DPTR, #LED3
	MOVX @DPTR, A
	RET
TAB_LED: DB 0C0H, 0F9H, 0A4H, 0B0H, 99H, 92H, 82H, 0F8H, 80H, 90H
;----------------------------------------
PROCESSING:
	MOV B, #100
	DIV AB
	MOV R2, A
	MOV A, B

	MOV B, #10
	DIV AB
	MOV R1, A
	MOV R0, B
;-----------------
	MOV A, R6
	CJNE A, #1, TTUC1
	CLR C
	MOV A, R0
	ADD A, #6
	DA A
	MOV C, ACC.4
	ANL A, #0FH
	MOV R0, A
	MOV A, R1
	ADDC A, #5
	DA A
	MOV C, ACC.4
	ANL A, #0FH
	MOV R1, A
	MOV A, R2
	ADDC A, #2
	MOV R2, A
	RET
;-----------------
	TTUC1:
	CJNE A, #2, TTUC2
	CLR C
	MOV A, R0
	ADD A, #2
	DA A
	MOV C, ACC.4
	ANL A, #0FH
	MOV R0, A

	MOV A, R1
	ADDC A, #1
	DA A
	MOV C, ACC.4
	ANL A, #0FH
	MOV R1, A

	MOV A, R2
	ADDC A, #5
	MOV R2, A
	RET
;-----------------	
	TTUC2:
	CJNE A, #3, TTUC3
	CLR C
	MOV A, R0
	ADD A, #8
	DA A
	MOV C, ACC.4
	ANL A, #0FH
	MOV R0, A

	MOV A, R1
	ADDC A, #6
	DA A
	MOV C, ACC.4
	ANL A, #0FH
	MOV R1, A

	MOV A, R2
	ADDC A, #7
	MOV R2, A
	RET

	TTUC3:
	RET

;----------------------------------------
DELAY:
	MOV TH1, #HIGH(-1000)
	MOV TL1, #LOW(-1000)
	SETB TR1
	JNB TF1, $
	CLR TR1
	CLR TF1
	RET

END